name: polkawallet_plugin_bifrost
description: Bifrost network plugin for polkawallet.
version: 0.3.2
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.13.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.22.0
  json_annotation: ^4.0.1
  get_storage: ^2.0.2
  device_info: ^2.0.1
  liquid_progress_indicator: ^0.3.2
  polkawallet_sdk: ^0.3.2
  polkawallet_ui: ^0.3.2

dev_dependencies:
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/js_service_bifrost/dist/main.js
    - assets/images/public/bifrost.png
    - assets/images/public/bifrost_gray.png
    - assets/images/tokens/BNC.png
    - assets/images/tokens/VSKSM.png
    - assets/images/tokens/KSM.png
    - assets/images/tokens/KUSD.png
    - assets/images/tokens/VSBOND.png
    - assets/images/assets_up.png
    - assets/images/assets_down.png
    - assets/images/assets_send.png
    - assets/images/scan.svg

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
