name: polkawallet_plugin_bifrost
description: A new Flutter package project.
version: 0.2.9
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.22.0
  get_storage: ^2.0.2
  graphql_flutter: ^5.0.0-nullsafety.5
  json_annotation: ^4.0.1
  polkawallet_sdk: ^0.2.9
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: 270a0b32f2361f451ee8348744097fde7addc8f4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - lib/js_service_bifrost/dist/main.js
    - assets/images/public/bg_bifrost.png
    - assets/images/public/bifrost.png
    - assets/images/public/bifrost_gray.png
    - assets/images/tokens/BNC.png
    - assets/images/tokens/vsKSM.png
    - assets/images/tokens/KSM.png
    - assets/images/tokens/KUSD.png
    - assets/images/tokens/vsBOND.png

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
