name: polkawallet_plugin_bifrost
description: The bifrost network flutter plugin for polkawallet app.
version: 0.1.6
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.0
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  json_annotation: ^3.0.1
  flutter_svg: ^0.19.3
  get_storage: ^1.2.1
  polkawallet_sdk: ^0.1.6
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: a71c448a632c77f9727925c06c17b5de49bf53ee

dev_dependencies:
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.1
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   polkawallet_ui:
#     path: ../ui
#   polkawallet_sdk:
#     path: ../sdk

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/js_api_bifrost/dist/main.js
    - assets/images/public/bg_bifrost.png
    - assets/images/public/bifrost.png
    - assets/images/public/bifrost_gray.png
    - assets/images/tokens/ASG.png
    - assets/images/public/polkassembly.png
    - assets/images/public/hero_icon.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
